### ISSUE TITLE
cordova plugin not working

### ISSUE THREAD

**Issue by pjc0247** [apache/cordova#126]
cordova plugin command not working 

Here's my log.
```
cordova plugin add cordova-plugin-fullscreen
? May Cordova anonymously report usage statistics to improve the tool over time? Yes

Thanks for opting into telemetry to help us improve cordova.
Unexpected token A in JSON at position 0
```

```
Attempting to use npm info for cordova-plugin-fullscreen to choose a compatible release
Running command: cmd "/s /c ""C:\Program Files\nodejs\npm.cmd" view cordova-plugin-fullscreen --json""
Command finished with error code 0: cmd /s /c ""C:\Program Files\nodejs\npm.cmd" view cordova-plugin-fullscreen --json"
Unexpected token A in JSON at position 0
SyntaxError: Unexpected token A in JSON at position 0
    at JSON.parse (<anonymous>)
    at C:\Users\pjc02\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\plugin\util.js:92:43
    at _fulfilled (C:\Users\pjc02\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:854:54)
    at C:\Users\pjc02\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (C:\Users\pjc02\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:13)
    at C:\Users\pjc02\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:624:44
    at runSingle (C:\Users\pjc02\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:137:13)
    at flush (C:\Users\pjc02\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:125:13)
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
```

**Comment by janpio** [comment]
Can not reproduce:

```
E:\Projects\throwaway
λ cordova create pluginFooTest
Creating a new cordova project.

E:\Projects\throwaway
λ cd pluginFooTest

E:\Projects\throwaway\pluginFooTest  (helloworld@1.0.0)
λ cordova plugin add cordova-plugin-fullscreen
Adding cordova-plugin-fullscreen to package.json
```

Uninstall Cordova and install it again, then try again and report here if it works please.
