### ISSUE TITLE
After upgrade cordova not able to run cordova from php exec() or shell_exec()

### ISSUE THREAD

**Issue by khankingtauseef** [apache/cordova#130]
# Bug Report

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by khankingtauseef** [comment]
After cordova update from 7.1.0 to latest 9.0.0, cordova -v run in terminal but when we use it with php exec('cordova -v') or shell_exex('cordova -v') or exec(`cordova -v`) not working, display below error.
Also when we downgrade cordova version from 9.0.0 to 6.0.0 it will worked.
please help us to solve this issue.

Array
(
    [0] => path.js:7
    [1] =>     throw new TypeError('Path must be a string. Received ' + inspect(path));
    [2] =>     ^
    [3] => 
    [4] => TypeError: Path must be a string. Received undefined
    [5] =>     at assertPath (path.js:7:11)
    [6] =>     at Object.join (path.js:1217:7)
    [7] =>     at Object. (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/util.js:31:31)
    [8] =>     at Module._compile (module.js:577:32)
    [9] =>     at Object.Module._extensions..js (module.js:586:10)
    [10] =>     at Module.load (module.js:494:32)
    [11] =>     at tryModuleLoad (module.js:453:12)
    [12] =>     at Function.Module._load (module.js:445:3)
    [13] =>     at Module.require (module.js:504:17)
    [14] =>     at require (internal/module.js:20:19)
    [15] => openjdk version "1.8.0_191"
    [16] => OpenJDK Runtime Environment (build 1.8.0_191-b12)
    [17] => OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
    [18] => v6.16.0
    [19] => 3.10.10
)

Thank you.

**Comment by khankingtauseef** [comment]
Also exec('npm -v), exec('node -v') and ('java -version') is working

**Comment by GedasGa** [comment]
It looks like you may not have the `HOME` env variable defined.

**Comment by khankingtauseef** [comment]
We already set PATH env variable, can you please let us know what we need to set in HOME env vaiable.

**Comment by GedasGa** [comment]
`HOME` should be a path to your User's home directory that has the `.cordova` folder inside.

**Comment by khankingtauseef** [comment]
We are using Centos 7 and don't have that directory.  I have searched for it but there is no directory.

**Comment by GedasGa** [comment]
Anyway, from your given information the problem is that you don't have a `HOME` path defined.

It fails in the following [statement in cordova-lib](https://github.com/apache/cordova-lib/blob/dfbab745d918de1cb24b2b0fe6bd1652ac2b227b/src/cordova/util.js#L29-L32).

What you could do, is to define a path, which can be accessed by the user that executes the command and create a `.cordova` folder with a `lib` folder inside. (even if the contents are empty, it should be fine)

**Comment by janpio** [comment]
Looks like a bug to me then, if Cordova requires a `HOME` env var that might not be set on all environments.

**Comment by GedasGa** [comment]
> Looks like a bug to me then, if Cordova requires a `HOME` env var that might not be set on all environments.

For windows, we require `USERPROFILE` variable and for Unix/Linux environments - `HOME`. `HOME` env variable Indicates the home directory of the current user and is the default argument for the `cd` built-in command. So I wouldn't necessarily say it's a bug.

**Comment by khankingtauseef** [comment]
We found the solution, some how after update nodeJs and cordova env variables are not working, only worked in cmd terminal, so need to add env variable in server script page, in my case i add putenv("CORDOVA_HOME=/usr/bin/cordova"); to find cordova location run 'which cordova' in cmd terminal it will give the cordova install location, after that can easily get all cordova cmd in server scripting(exec('cordova -v')).

Thank you guys for help.
