### ISSUE TITLE
🦟`cordova build ios` for a blank project fails with an unknown error

### ISSUE THREAD

**Issue by kas-kad** [apache/cordova#176]
# Bug Report

```
➜  ~ cordova create HelloWorld                                                
Creating a new cordova project.
➜  ~ cd HelloWorld 
➜  HelloWorld cordova platform add ios
Using cordova-fetch for cordova-ios@~4.5.4
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: io.cordova.hellocordova
	Name: HelloCordova
iOS project created with cordova-ios@4.5.5
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for ios
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
--save flag or autosave detected
Saving ios@~4.5.5 into config.xml file ...
➜  HelloWorld cordova build ios -verbose
No scripts found for hook "before_build".
No scripts found for hook "before_prepare".
Checking config.xml and package.json for saved platforms that haven't been added to the project
Config.xml and package.json platforms are the same. No pkg.json modification.
Package.json and config.xml platforms are different. Updating config.xml with most current list of platforms.
PlatformApi successfully found for platform ios
Checking config.xml for saved plugins that haven't been added to the project
Checking for any plugins added to the project that have not been installed in ios platform
No differences found between plugins added to project and installed in ios platform. Continuing...
Generating platform-specific config.xml from defaults for iOS at /Users/mobile_ci/HelloWorld/platforms/ios/HelloCordova/config.xml
Merging project's config.xml into platform-specific iOS config.xml
Merging and updating files from [www, platforms/ios/platform_www] to platforms/ios/www
Current launch storyboard undefined
Not changing launch storyboard setting in info plist.
Wrote out iOS Bundle Identifier "io.cordova.hellocordova" and iOS Bundle Version "1.0.0" to /Users/mobile_ci/HelloWorld/platforms/ios/HelloCordova/HelloCordova-Info.plist
No need to update build settings for launch storyboard support.
iOS Product Name has not changed (still "HelloCordova")
This app does not have icons defined
This app does not have splash screens defined
Updating launch storyboard images at platforms/ios/HelloCordova/Images.xcassets/LaunchStoryboard.imageset/
Updating Storyboard image set contents.json
This app does not have additional resource files defined
Prepared iOS project successfully
No scripts found for hook "after_prepare".
No scripts found for hook "before_compile".
Error
    at cli.catch.err (/usr/local/lib/node_modules/cordova/bin/cordova:29:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

### Version information
```
Catalina 10.15.1
cordova 9.0.0 (cordova-lib@9.0.1)
npm 6.13.1
xcodebuild Xcode 11.1 Build version 11A1027
```

**Comment by raphinesse** [comment]
Cordova 9 should install `cordova-ios@^5.0.0` when given no explicit version. Can you please double check that you are _actually_ using `cordova@9`?

**Comment by kas-kad** [comment]
Ok, I removed cordova completely with `npm uninstall -g cordova`, after that `cordova build` started failing with `command not found`. Also, I uninstalled cordova-ios@4.5.5 manually with `npm uninstall -g cordova-ios`. After reinstalling cordova@9.0.0 (`sudo npm install cordova -g`) I repeated the `cordova create HelloWorld`...

```
➜  HelloWorld cordova platform add ios
Using cordova-fetch for cordova-ios@^5.0.0
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: io.cordova.hellocordova
	Name: HelloCordova
iOS project created with cordova-ios@5.1.0
Plugin 'cordova-plugin-whitelist' found in config.xml... Migrating it to package.json
Plugin 'com-infobip-plugins-mobilemessaging' found in config.xml... Migrating it to package.json
Discovered saved plugin "cordova-plugin-whitelist". Adding it to the project
Installing "cordova-plugin-whitelist" for ios
Adding cordova-plugin-whitelist to package.json
Discovered saved plugin "com-infobip-plugins-mobilemessaging". Adding it to the project
Installing "com-infobip-plugins-mobilemessaging" for ios
Installing "cordova-plugin-add-swift-support" for ios
Installing "cordova-custom-config" for ios
Running command: /Users/mobile_ci/HelloWorld/plugins/com-infobip-plugins-mobilemessaging/scripts/build_mobile_messaging_framework.sh /Users/mobile_ci/HelloWorld
Building MobileMessaging.framework with Carthage started...
*** Checking out mobile-messaging-sdk-ios at "5.3.1"
*** xcodebuild output can be found in /var/folders/bf/xbk6fmld26zfg2xppv65vn740000gn/T/carthage-xcodebuild.Yg7AEl.log
*** Invalid cache found for mobile-messaging-sdk-ios, rebuilding with all downstream dependencies
*** Building scheme "DebugMobileMessaging" in MobileMessaging.xcodeproj
*** Building scheme "MobileMessaging" in MobileMessaging.xcodeproj
Building MobileMessaging.framework with Carthage finished.
/Users/mobile_ci/HelloWorld
Adding com-infobip-plugins-mobilemessaging to package.json
cordova-custom-config: Applied custom config from config.xml to /Users/mobile_ci/HelloWorld/platforms/ios/HelloCordova/HelloCordova-Info.plist
Update IOS build setting SWIFT_OBJC_BRIDGING_HEADER to: "$(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h" for build configuration Debug
Update IOS build setting SWIFT_OBJC_BRIDGING_HEADER to: "$(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h" for build configuration Release
Update IOS build setting ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES to: YES for build configuration Debug
Update SWIFT version to 4.0 Debug
Update IOS build setting SWIFT_OPTIMIZATION_LEVEL to: -Onone for build configuration Debug
Update IOS build setting ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES to: YES for build configuration Release
Update SWIFT version to 4.0 Release
+ cordova-custom-config@5.1.0
updated 1 package and audited 215 packages in 1.989s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


➜  HelloWorld cordova build ios                                                                 
cordova-custom-config: Skipping auto-restore of config file backup(s)
cordova-custom-config: Applied custom config from config.xml to /Users/mobile_ci/HelloWorld/platforms/ios/HelloCordova/HelloCordova-Info.plist
Error
    at cli.catch.err (/usr/local/lib/node_modules/cordova/bin/cordova:29:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)
➜  HelloWorld npm list | grep cordova                                                   
npm WARN npm npm does not support Node.js v7.7.4
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12, 13.
npm WARN npm You can find the latest version at https://nodejs.org/
├── com-infobip-plugins-mobilemessaging@1.1.5 -> /Users/mobile_ci/jenkins/workspace/infobip-mobile-messaging-cordova-plugin-build-ios
├─┬ cordova-custom-config@5.1.0
├─┬ cordova-ios@5.1.0
│ ├─┬ cordova-common@3.2.1
├─┬ cordova-plugin-add-swift-support@2.0.2
└── cordova-plugin-whitelist@1.3.4
➜  HelloWorld npm list -g | grep cordova
npm WARN npm npm does not support Node.js v7.7.4
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12, 13.
npm WARN npm You can find the latest version at https://nodejs.org/
├─┬ cordova@9.0.0
│ ├─┬ cordova-common@3.2.1
│ ├─┬ cordova-lib@9.0.1
│ │ ├── cordova-common@3.2.1 deduped
│ │ ├─┬ cordova-create@2.0.0
│ │ │ ├── cordova-app-hello-world@4.0.0
│ │ │ ├── cordova-common@3.2.1 deduped
│ │ │ ├── cordova-fetch@2.0.1 deduped
│ │ ├─┬ cordova-fetch@2.0.1
│ │ │ ├── cordova-common@3.2.1 deduped
│ │ ├─┬ cordova-serve@3.0.0
➜  HelloWorld 
```

**Comment by raphinesse** [comment]
OK, so the first thing is sorted out. Now I noticed two things with your Node.js setup that you should address:
- Install a maintained Node.js version (I would recommend v12)
- Adapt your npm setup so that you can use [`npm` without `sudo`](https://www.google.com/search?q=npm+without+sudo)

**Comment by kas-kad** [comment]
after updating Nodejs, I started getting a meaningful error message from cordova
```
CordovaError: Promise rejected with non-error: "Cordova needs ios-deploy version 1.9.2 or greater, you have version 1.9.1. Please download, build and install version 1.9.2 or greater from https://github.com/ios-control/ios-deploy into your path, or do 'npm install -g ios-deploy'"
```
there was another challenge installing a newer version of ios-deploy, but I've succeeded with help from this topic https://github.com/ios-control/ios-deploy/issues/415.

**Comment by raphinesse** [comment]
Great to hear that! I'm glad I could help you.
