### ISSUE TITLE
Cordova-Android build fails on Azure pipeline whereas the same project work perfectly fine on local build

### ISSUE THREAD

**Issue by EeshaRoy** [apache/cordova#221]
Hello Cordova build android pipeline on Azure DevOps is throwing error with old cordova version or latest version. But grunt build android is running perfectly fine on my local project.  So I believe this is some problem with new version of some tasks. Could you look and fix it ?

Thanks,

### What is expected to happen?
Build is supposed to finish successfully by running all scripts  the same project work perfectly fine on my local build
![image](https://user-images.githubusercontent.com/67674499/86205728-3c236b80-bb30-11ea-82d3-46b3d5f616ac.png)

### What does actually happen?

##[section]Starting: Cordova Build android
2020-06-30T14:28:09.1569434Z ##[section]Starting: Cordova Build android
2020-06-30T14:28:09.1986970Z ==============================================================================
2020-06-30T14:28:09.1987541Z Task         : Cordova Build
2020-06-30T14:28:09.1988130Z Description  : Build a hybrid app project based on the Cordova CLI, Ionic CLI, TACO CLI, or other Cordova-compliant CLI
2020-06-30T14:28:09.1988748Z Version      : 1.3.12
2020-06-30T14:28:09.1989150Z Author       : Microsoft Corporation
2020-06-30T14:28:09.1989715Z Help         : [More Information](http://go.microsoft.com/fwlink/?LinkID=691186)
2020-06-30T14:28:09.1990328Z ==============================================================================
2020-06-30T14:28:10.0943023Z Module cache at C:\Users\VssAdministrator\AppData\Roaming\taco_home\node_modules
2020-06-30T14:28:12.1530642Z Installing cordova to C:\Users\VssAdministrator\AppData\Roaming\taco_home\node_modules\cordova\9.0.0. (This may take a few minutes.)
2020-06-30T14:28:49.8644198Z Exec complete.
2020-06-30T14:28:49.8645079Z npm WARN using --force I sure hope you know what you are doing.
2020-06-30T14:28:49.8645622Z npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
2020-06-30T14:28:49.8646383Z npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
2020-06-30T14:28:49.8647161Z npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
2020-06-30T14:28:49.8648054Z npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\VssAdministrator\AppData\Roaming\taco_home\node_modules\cordova\9.0.0\package.json'
2020-06-30T14:28:49.8648865Z npm notice created a lockfile as package-lock.json. You should commit this file.
2020-06-30T14:28:49.8649608Z npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\VssAdministrator\AppData\Roaming\taco_home\node_modules\cordova\9.0.0\package.json'
2020-06-30T14:28:49.8651538Z npm WARN 9.0.0 No description
2020-06-30T14:28:49.8652075Z npm WARN 9.0.0 No repository field.
2020-06-30T14:28:49.8657924Z npm WARN 9.0.0 No README data
2020-06-30T14:28:49.8658284Z npm WARN 9.0.0 No license field.
2020-06-30T14:28:49.8658510Z 
2020-06-30T14:28:49.8658725Z + cordova@9.0.0
2020-06-30T14:28:49.8660020Z added 432 packages from 355 contributors and audited 432 packages in 36.268s
2020-06-30T14:28:49.8660637Z 
2020-06-30T14:28:49.8660889Z 3 packages are looking for funding
2020-06-30T14:28:49.8661221Z   run `npm fund` for details
2020-06-30T14:28:49.8661418Z 
2020-06-30T14:28:49.8661638Z found 0 vulnerabilities
2020-06-30T14:28:49.8661824Z 
2020-06-30T14:28:49.8661983Z 
2020-06-30T14:28:53.1350051Z Adding ant.properties update hook
2020-06-30T14:28:56.5720896Z Module cache at C:\Users\VssAdministrator\AppData\Roaming\taco_home\node_modules
2020-06-30T14:28:58.3840929Z cordova already installed.
2020-06-30T14:28:58.3848166Z Adding support plugin.
2020-06-30T14:29:00.2569681Z Removing ant.properties update hook
2020-06-30T14:29:00.2607733Z TypeError: Cannot read property 'plugin' of undefined
2020-06-30T14:29:00.2608687Z     at D:\a\_tasks\CordovaBuild_70e94267-15dc-434d-8973-023d766825d7\1.3.12\node_modules\taco-team-build\taco-team-build.js:66:37
2020-06-30T14:29:00.2609634Z     at _fulfilled (D:\a\_tasks\CordovaBuild_70e94267-15dc-434d-8973-023d766825d7\1.3.12\node_modules\q\q.js:854:54)
2020-06-30T14:29:00.2610635Z     at D:\a\_tasks\CordovaBuild_70e94267-15dc-434d-8973-023d766825d7\1.3.12\node_modules\q\q.js:883:30
2020-06-30T14:29:00.2612386Z     at Promise.promise.promiseDispatch (D:\a\_tasks\CordovaBuild_70e94267-15dc-434d-8973-023d766825d7\1.3.12\node_modules\q\q.js:816:13)
2020-06-30T14:29:00.2613817Z     at D:\a\_tasks\CordovaBuild_70e94267-15dc-434d-8973-023d766825d7\1.3.12\node_modules\q\q.js:624:44
2020-06-30T14:29:00.2616905Z     at runSingle (D:\a\_tasks\CordovaBuild_70e94267-15dc-434d-8973-023d766825d7\1.3.12\node_modules\q\q.js:137:13)
2020-06-30T14:29:00.2617974Z     at flush (D:\a\_tasks\CordovaBuild_70e94267-15dc-434d-8973-023d766825d7\1.3.12\node_modules\q\q.js:125:13)
2020-06-30T14:29:00.2620041Z     at processTicksAndRejections (internal/process/task_queues.js:79:11)
2020-06-30T14:29:00.2975480Z ##[error]Task failed
2020-06-30T14:29:00.2993888Z (node:5656) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-06-30T14:29:00.2994474Z (node:5656) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-06-30T14:29:00.2994994Z (node:5656) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-06-30T14:29:00.2995478Z (node:5656) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-06-30T14:29:00.2996195Z (node:5656) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-06-30T14:29:00.2996851Z (node:5656) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-06-30T14:29:00.2997189Z (node:5656) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-06-30T14:29:00.2997520Z (node:5656) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-06-30T14:29:00.2997873Z (node:5656) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-06-30T14:29:00.2998215Z (node:5656) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-06-30T14:29:00.2998542Z (node:5656) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-06-30T14:29:00.2998888Z (node:5656) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-06-30T14:29:00.2999218Z (node:5656) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-06-30T14:29:00.2999565Z (node:5656) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-06-30T14:29:00.2999892Z (node:5656) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-06-30T14:29:00.3000218Z (node:5656) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-06-30T14:29:00.3000562Z (node:5656) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-06-30T14:29:00.3000891Z (node:5656) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-06-30T14:29:00.3001716Z (node:5656) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-06-30T14:29:00.3002074Z (node:5656) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-06-30T14:29:00.3002399Z (node:5656) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-06-30T14:29:00.3002727Z (node:5656) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-06-30T14:29:00.3004212Z (node:5656) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-06-30T14:29:00.3107477Z ##[section]Finishing: Cordova Build android

## Information
You can see the list of plugins with versions
![image](https://user-images.githubusercontent.com/67674499/86206069-1f3b6800-bb31-11ea-9120-aa38b3a56da4.png)

![image](https://user-images.githubusercontent.com/67674499/86206624-72fa8100-bb32-11ea-9698-747f0cdd9b17.png)

### Command or Code
Cordova build Android

### Environment, Platform, Device
This issue is happening on Azure pipelines and even if I use cordova android version 8.1.0 the issue is same build fails on cordova build android script or cordova prepare android script. The same pipeline used to work with cordova 6 version previously but from june first week it started failing, so tried updating all plugin versions and cordova version to latest and local build work perfectly fine I am able to get debug apk. But to deploy changes release apk is failing at those shown scripts

## Checklist

- 

- [x] -  I searched for existing GitHub issues

- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
Like Norman already said in your other issue:
> Based on the stacktrace, the issue appears to be inside taco-team-build package.

Unfortunately, we can't help with issues that are coming from cloud providers. I assume you need to seek support via Azure/taco-team-build.
