### ISSUE TITLE
Android / Web / iOSThe "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by BonBonSlick** [apache/cordova#239]
# Bug Report
Tested with platforms: android, android@7.1.1, android@7.0.1, cordova-android@nightly, android@8. All broken.

## Problem
After PC restart or apt update / upgrade cordova is broken.
Tried to reinstall platform, clear cache and lean everything. 

### What is expected to happen?
build successfull

### What does actually happen?
errors and warnings
1 - error that path ===undefined
2 - warning that sdk missing while it exists and set in $path

### Command or Code

any build, clean
```
bonbon@debian:/var/www/123/cordova$ cordova platform add android
Using cordova-fetch for cordova-android@^8.1.0
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms/android
        Package: com.test.sample
        Name: test
        Activity: MainActivity
        Android target: android-28
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@8.1.0
--->> config file undefined requested for changes not found at /var/www/123/cordova/platforms/android/undefined, ignoring
--->> config file undefined requested for changes not found at /var/www/123/cordova/platforms/android/undefined, ignoring
Discovered saved plugin "cordova-plugin-whitelist". Adding it to the project
Installing "cordova-plugin-whitelist" for android
Adding cordova-plugin-whitelist to package.json
...
Adding cordova-plugin-health to package.json
Discovered saved plugin "cordova-plugin-background-mode". Adding it to the project
Installing "cordova-plugin-background-mode" for android
--->> android-sdk version check failed (/var/www/test/cordova/platforms/android/cordova/android_sdk_version), continuing anyways.
Installing "cordova-plugin-device" for android
Adding cordova-plugin-background-mode to package.json
--->> config file undefined requested for changes not found at /var/www/test/cordova/platforms/android/undefined, ignoring
--->> config file undefined requested for changes not found at /var/www/test/cordova/platforms/android/undefined, ignoring
--->> The "path" argument must be of type string. Received type undefined
```

```

bonbon@debian:/var/www/test/cordova$ cordova plugin remove cordova-plugin-anyPackage
Uninstalling cordova-plugin-anyPackage from android
Uninstalling cordova-plugin-anyPackage from browser
js-module uninstall called : plugins/cordova-plugin-anyPackage/www/anyPackage.js
Removing "cordova-plugin-anyPackage"
Removing cordova-plugin-anyPackage from package.json
config file undefined requested for changes not found at /var/www/test/cordova/platforms/android/undefined, ignoring
config file undefined requested for changes not found at /var/www/test/cordova/platforms/android/undefined, ignoring
The "path" argument must be of type string. Received type undefined
```
```


bonbon@debian:/var/www/test/cordova$ cordova prepare
config file undefined requested for changes not found at /var/www/testconfig file undefined requested for changes not found at /var/www/test/cordova/platforms/android/undefined, ignoring
The "path" argument must be of type string. Received type undefined

```

### Environment, Platform, Device

Debian 9

### Version information

/et/environment
```
JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/jre/"
ANDROID_HOME=$HOME/Android/Sdk
ANDROID_SDK_ROOT=$HOME/Android/Sdk

```
```
bonbon@debian:~$ echo $PATH
/home/bonbon/.yarn/bin:/home/bonbon/.config/yarn/global/node_modules/.bin:$HOME/Android/Sdk/platform-tools:$HOME/Android/Sdk/tools:/opt/gradle/gradle-6.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin

bonbon@debian:~$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0+deb9u1-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)

bonbon@debian:/var/www/test/cordova$ cordova --version 
9.0.0 (cordova-lib@9.0.1)

bonbon@debian:~/Android/Sdk/build-tools$ ls -la
total 20
drwxr-xr-x  5 bonbon bonbon 4096 Aug 31 06:58 .
drwxr-xr-x 14 bonbon bonbon 4096 Aug 31 06:58 ..
drwxr-xr-x  5 bonbon bonbon 4096 Jul 30 21:21 28.0.3
drwxr-xr-x  6 bonbon bonbon 4096 Jul 30 20:08 30.0.1
drwxr-xr-x  6 bonbon bonbon 4096 Aug 31 06:58 30.0.2


Requirements check results for android:
Java JDK: installed 1.8.0
Android SDK: installed true
Android target: installed android-30,android-28,android-27
Gradle: installed /opt/gradle/gradle-6.3/bin/gradle

```
```
 "dependencies": {
    "cordova-android": "^8.1.0",
    "cordova-browser": "^6.0.0",
    "cordova-plugin-background-mode": "^0.7.3",
    "cordova-plugin-customurlscheme": "^5.0.2",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-geolocation": "^4.0.2",
    "cordova-plugin-health": "^1.1.5",
    "cordova-plugin-stepcounter": "git+https://github.com/ihadeed/cordova-plugin-stepcounter.git",
    "cordova-plugin-stepper": "^0.1.4"
  },
  "devDependencies": {
    "cordova-plugin-whitelist": "^1.3.4"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-customurlscheme": {
        "URL_SCHEME": "localhost",
        "ANDROID_SCHEME": " ",
        "ANDROID_HOST": " ",
        "ANDROID_PATHPREFIX": "/"
      },
      "cordova-plugin-geolocation": {},
      "cordova-plugin-stepper": {},
      "cordova-plugin-stepcounter": {},
      "cordova-plugin-health": {
        "HEALTH_READ_PERMISSION": "App needs read access",
        "HEALTH_WRITE_PERMISSION": "App needs write access",
        "GMS_VERSION": "16.0.1"
      },
      "cordova-plugin-background-mode": {},
      "cordova-plugin-device": {}
    },
```

## Checklist

- [ x] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by BonBonSlick** [comment]
added --verbose 

```
bonbon@debian:/var/www/test/cordova$ cordova platform add android --verbose
No scripts found for hook "before_platform_add".
No version supplied. Retrieving version from config.xml...
Grabbing pinned version.
Using cordova-fetch for cordova-android@^8.0.0
fetch: Installing cordova-android@^8.0.0 to /var/www/test/cordova
Running command: npm install cordova-android@^8.0.0 --production --save
Command finished with error code 0: npm install,cordova-android@^8.0.0,--production,--save
Removing "cordova-" prefix from cordova-android
Adding android project...
PlatformApi successfully found for platform android
Creating Cordova project for the Android platform:
        Path: platforms/android
        Package: com.sgx.sample
        Name: SGX_Charity_Run
        Activity: MainActivity
        Android target: android-28
Copying android template project to platforms/android
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@8.1.0
.. many grey stuff ...
config file undefined requested for changes not found at /var/www/test/cordova/platforms/android/undefined, ignoring
config file undefined requested for changes not found at /var/www/test/cordova/platforms/android/undefined, ignoring
Installing plugin "cordova-plugin-background-mode" following successful platform add of android
Found variables for "cordova-plugin-background-mode". Processing as cli_variables.
Installing "cordova-plugin-background-mode" for android
Running command: /var/www/test/cordova/platforms/android/cordova/version 
Command finished with error code 0: /var/www/test/cordova/platforms/android/cordova/version 
Running command: /var/www/test/cordova/platforms/android/cordova/android_sdk_version 
Command finished with error code 2: /var/www/test/cordova/platforms/android/cordova/android_sdk_version 
android-sdk version check failed (/var/www/test/cordova/platforms/android/cordova/android_sdk_version), continuing anyways.
Dependencies detected, iterating through them...
Requesting plugin "cordova-plugin-device".
Plugin dependency "cordova-plugin-device@2.0.3" already fetched, using that version.
Installing "cordova-plugin-device" for android
....
No differences found between plugins added to project and installed in android platform. Continuing...
Generating platform-specific config.xml from defaults for android at /var/www/test/cordova/platforms/android/app/src/main/res/xml/config.xml
config file undefined requested for changes not found at /var/www/test/cordova/platforms/android/undefined, ignoring
config file undefined requested for changes not found at /var/www/test/cordova/platforms/android/undefined, ignoring
Merging project's config.xml into platform-specific android config.xml
[Gradle Properties] Preparing Configuration
...
Prepared android project successfully
The "path" argument must be of type string. Received type undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1147:7)
    at ConfigKeeper_get [as get] (/usr/lib/node_modules/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigKeeper.js:45:26)
    at /usr/lib/node_modules/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:346:51
    at Array.forEach (<anonymous>)
    at is_conflicting (/usr/lib/node_modules/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:339:17)
    at PlatformMunger.add_config_changes (/usr/lib/node_modules/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:190:33)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/prepare.js:112:32
    at _fulfilled (/var/www/test/cordova/node_modules/q/q.js:854:54)
    at /var/www/test/cordova/node_modules/q/q.js:883:30
```
[Might be related issue SO](https://stackoverflow.com/questions/55570278/cordova-error-due-to-8-0-the-path-argument-must-be-of-type-string-received-ty)

**Comment by BonBonSlick** [comment]
Adding `export CORDOVA_HOME="~/.cordova"` will not help but add more errors. Because there is no folder in ~/ root directory. But it seems that might be the key
```

Yet, after playing with it a lot I found out that the actual problem is with util.js file under /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/util.js and the problem was with the following line: global_config_path = path.join(HOME, '.cordova');

This code executes only in case CORDOVA_HOME environment variable does not exist. So I've just added it: export CORDOVA_HOME="~/.cordova" and the exception was gone. Hope it'll help someone.
```

right now platform is added, but build failing.

**Comment by BonBonSlick** [comment]
Btw, we do not have plugin.xml for plugin configs, all configs are in package.json
```
"cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-customurlscheme": {
        "URL_SCHEME": "localhost",
```
or in js.

Cordova ocnfig.xml
```

<?xml version='1.0' encoding='utf-8'?>
<widget id="com.test.sample" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>
        test 
    </name>
    <description>
        A sample     application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
          BonBonSlick
    </author>
    <content src="./index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <config-file parent="NSHealthShareUsageDescription" platform="ios">
        <string>App needs read access</string>
    </config-file>
    <config-file parent="NSHealthUpdateUsageDescription" platform="ios">
        <string>App needs write access</string>
    </config-file>
</widget>

```

**Comment by BonBonSlick** [comment]
```
sudo chmod -R 775 /your/proj/path/
sudo chmod -R 775 /your/proj/path/cordova
sudo chmod -R 775 /your/proj/path/cordova/platforms

sudo chown -R www-data:www-data  projpath
sudo chown -R www-data:www-data  
sudo chown -R www-data:www-data  projpath/cordova/platforms
```

**Solvs issues with  path error**

But more to go.

1- 
`android-sdk version check failed (/var/www/charity_run_ui/cordova/platforms/android/cordova/android_sdk_version), continuing anyways.
`

2-
```
Installing "cordova-plugin-whitelist" for android
shell.js: internal error
Error: EPERM: operation not permitted, chmod '/var/www/test/cordova/platforms/browser/config.xml'
    at Object.chmodSync (fs.js:1027:3)
    at copyFileSync (/var/www/test/cordova/node_modules/shelljs/src/cp.js:41:6)
    at /var/www/test/cordova/node_modules/shelljs/src/cp.js:201:5
    at Array.forEach (<anonymous>)
    at Object._cp (/var/www/test/cordova/node_modules/shelljs/src/cp.js:157:11)
    at Object.cp (/var/www/test/cordova/node_modules/shelljs/src/common.js:186:23)
    at Api.prepare (/var/www/test/cordova/platforms/browser/cordova/Api.js:145:15)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/prepare.js:105:36
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)

```
2 - app is slowered, need to click button couples times before it reacts  
3 - app closing itself time to time!?|
4 - app opens itself (hide and open, go to background and foreground)
5 - **breaks other plugins!** For example  [that](https://github.com/ihadeed/cordova-plugin-stepcounter#readme) returns always 0 steps with enabled backgroundmode true

**Comment by breautek** [comment]
> Tested with platforms: android, android@7.1.1, android@7.0.1, cordova-android@nightly, android@8. All broken.

These are all unsupported platforms. `cordova-android@9` is the latest version. This version also migrated away from using `shelljs` both for security, and better cross-platform support.

Also generally speaking, cordova project files should be owned as your logged in user, not `www-data`. If you have to change the ownership of your cordova project, then you should also make sure that you're using cordova commands under the correct user.

**Comment by brettr91** [comment]
We were having similar issues, we uninstalled Node, purged user data of npm and npm-cache folders. Reinstalled Node and it solved the problem.

**Comment by breautek** [comment]
Closing due to staleness.
