### ISSUE TITLE
Not able to add ios platform using node version 11.15.0

### ISSUE THREAD

**Issue by tm-ssingh** [apache/cordova#275]
Keep getting below error:

ReferenceError: globalThis is not defined
    at Object.<anonymous> (/Users/sukhwinder/Documents/hiApp_Project/Source_code_upgrade_nets_sdk/cordova/node_modules/run-parallel/node_modules/queue-microtask/index.js:5:25)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/sukhwinder/Documents/hiApp_Project/Source_code_upgrade_nets_sdk/cordova/node_modules/run-parallel/index.js:4:24)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)

Understood its because of queue-microtask dependency which as started making use of globalThis which is not supported on node v11. Can cordova-ios avoid using this dependency?

**Comment by breautek** [comment]
Non-LTS versions of Node is not supported.

We support the latest releases of each major LTS version going back to Node 10. I'd recommend upgrading to Node 14. If something prevents you from upgrading to Node 14, then the latest release of Node 12 or Node 10 should also work.

Duplicate: https://github.com/apache/cordova-android/issues/1162
