### ISSUE TITLE
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by josegamboa** [apache/cordova#350]
Hi guys,

I have tried to install Cordova on Mac OS 13 and it seems like there is  problem with lates versions, tried to install cordova 10 and 11 and I got same error.

# Bug Report
 Mac OS 13 Ventura

## Problem
I have installed Cordova 10.0.0 NodeJs 14 and it seems like there is an issue

` npm install -g  cordova@10.0.0  `
`cordova - version`

### What is expected to happen?
To return Cordova version 

### What does actually happen?
Returning an exception

## Information
`TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at macosRelease (/usr/local/lib/node_modules/cordova/node_modules/macos-release/index.js:28:26)
    at osName (/usr/local/lib/node_modules/cordova/node_modules/os-name/index.js:21:18)
    at new Insight (/usr/local/lib/node_modules/cordova/node_modules/insight/lib/index.js:37:13)
    at new RelentlessInsight (/usr/local/lib/node_modules/cordova/src/telemetry.js:31:1)
    at Object.<anonymous> (/usr/local/lib/node_modules/cordova/src/telemetry.js:39:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)`

### Command or Code
`cordova - version`

### Environment, Platform, Device
Mac OS 13 - Ventura

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by josegamboa** [comment]
It seems like this issue is related to the OS Version not yet listed at: /usr/local/lib/node_modules/cordova/node_modules/macos-release/index.js

Before:
const nameMap = new Map([
        [21, ['Monterey', '12']],
        [20, ['Big Sur', '11']],
        [19, ['Catalina', '10.15']],
        [18, ['Mojave', '10.14']],
        [17, ['High Sierra', '10.13']],
        [16, ['Sierra', '10.12']],
        [15, ['El Capitan', '10.11']],
        [14, ['Yosemite', '10.10']],
        [13, ['Mavericks', '10.9']],
        [12, ['Mountain Lion', '10.8']],
        [11, ['Lion', '10.7']],
        [10, ['Snow Leopard', '10.6']],
        [9, ['Leopard', '10.5']],
        [8, ['Tiger', '10.4']],
        [7, ['Panther', '10.3']],
        [6, ['Jaguar', '10.2']],
        [5, ['Puma', '10.1']]
]);

After:
const nameMap = new Map([
        [22, ['Ventura','13']],
        [21, ['Monterey', '12']],
        [20, ['Big Sur', '11']],
        [19, ['Catalina', '10.15']],
        [18, ['Mojave', '10.14']],
        [17, ['High Sierra', '10.13']],
        [16, ['Sierra', '10.12']],
        [15, ['El Capitan', '10.11']],
        [14, ['Yosemite', '10.10']],
        [13, ['Mavericks', '10.9']],
        [12, ['Mountain Lion', '10.8']],
        [11, ['Lion', '10.7']],
        [10, ['Snow Leopard', '10.6']],
        [9, ['Leopard', '10.5']],
        [8, ['Tiger', '10.4']],
        [7, ['Panther', '10.3']],
        [6, ['Jaguar', '10.2']],
        [5, ['Puma', '10.1']]
]);

After adding : [22, ['Ventura','13']], worked fine.

**Comment by breautek** [comment]
[macos-release](https://github.com/sindresorhus/macos-release/releases/tag/v3.1.0) has support for MacOS 13 now. If you run `npm upgrade -g cordova` to upgrade child dependencies, you may receive v3.1.0.

I don't think we directly depend `macos-release`.

If the upgrade command doesn't work, you may need to upgrade packages, using `cordova@11` and potentially the latest cordova-ios version.

**Comment by breautek** [comment]
Scratch, most of what I said

```bash
macosrelease@1.0.0 /home/norman/macosrelease
└─┬ cordova@11.0.0
  └─┬ insight@0.11.1
    └─┬ os-name@4.0.1
      └── macos-release@2.5.0
```

Seems like `macos-release` ultimately gets included because of our `insight` dependency. Moving this over to our CLI repo.
