### ISSUE TITLE
build failled after change phonegap-version to CLI 8.0

### ISSUE THREAD

**Issue by thienban** [apache/cordova#45]
Hi, i changed CLI 8.0 to use the plugin background-geolocation

Details of PhoneGap Build :
App ID
3354120
PhoneGap (iOS / Android / Windows)
cli-8.0.0 (4.5.4 / 7.0.0 / 5.0.0)
Source
.zip package
 
I changed my config.xml like below 👍 
```
<plugin name="cordova-background-geolocation-lt" spec="2.12.0" source="npm">  
<preference name='phonegap-version' value='cli-8.0.0' /> 
```

my plugins in config.xml
```
<plugin name="cordova-plugin-barcodescanner" spec="0.7.0" source="npm" />
<plugin name="cordova-plugin-battery-status" spec="2.0.1" source="npm" />
<plugin name="cordova-plugin-camera" spec="2.4.1" source="npm">
<plugin name="cordova-plugin-dialogs" spec="1.2.1" source="npm" />
<plugin name="cordova-plugin-file" spec="4.2.0" source="npm" />
<plugin name="cordova-plugin-file-transfer" spec="1.5.1" source="npm" />
<plugin name="cordova-plugin-geolocation" spec="2.4.3" source="npm">
<plugin name="cordova-plugin-globalization" spec="1.0.3" source="npm" />
<plugin name="cordova-plugin-inappbrowser" spec="2.0.2" source="npm" />
<plugin name="cordova-plugin-network-information" spec="1.2.1" source="npm" />
<plugin name="cordova-plugin-splashscreen" spec="3.2.2" source="npm" />
<plugin name="cordova-plugin-whitelist" spec="1.3.3" source="npm" /> 
<plugin name="cordova-background-geolocation-lt" spec="2.12.0" source="npm">
</plugin>  <plugin name="cordova-plugin-secure-key-store" spec="1.5.5" source="npm" />
```

My log from Phone Gap Build
`Error: ENOENT: no such file or directory, open '/tmp/gimlet/21220720/3358504/www_android/project/AndroidManifest.xml' `

```
Build Date: 2018-10-31 16:21:44 +0000  
--------------------------------------------------------------------------------  
PLUGIN OUTPUT  
--------------------------------------------------------------------------------  
"plugman-151 install --platform android --project /project --plugin cordova-plugin-barcodescanner@~0.7.0 --nohooks=.": Fetching plugin "cordova-plugin-barcodescanner@~0.7.0" via npm  
Installing "cordova-plugin-barcodescanner" at "0.7.4" for android  
Fetching plugin "cordova-plugin-compat@^1.0.0" via npm  
Installing "cordova-plugin-compat" at "1.2.0" for android  
Plugin doesn't support this project's cordova-android version. cordova-android: 7.0.0, failed version requirement:   
  <6.3.0  
Skipping 'cordova-plugin-compat' for android  
Failed to install 'cordova-plugin-barcodescanner': Error: ENOENT: no such file or directory, open '/tmp/gimlet/21220720/3358504/www_android/project/AndroidManifest.xml'  
  at Error (native)  
  at Object.fs.openSync (fs.js:640:18)  
  at Object.fs.readFileSync (fs.js:508:33)  
  at Object.parseElementtreeSync (/project/cordova/node_modules/cordova-common/src/util/xml-helpers.js:180:27)  
  at new AndroidManifest (/project/cordova/lib/AndroidManifest.js:29:20)  
  at AndroidProject.getPackageName (/project/cordova/lib/AndroidProject.js:99:12)  
  at Api.addPlugin (/project/cordova/Api.js:223:57)  
  at handleInstall (/usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/pgb-cordova-lib/src/plugman/install.js:594:10)  
  at /usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/pgb-cordova-lib/src/plugman/install.js:364:24  
  at _fulfilled (/usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:787:54)  
ENOENT: no such file or directory, open '/project/AndroidManifest.xml'  
```
Related to this post [https://stackoverflow.com/questions/47926796/cordova-does-not-create-androidmanifest-xml?noredirect=1&lq=1](url), I tried downgrade to cordova  to CLI 7.1.0. It's OK but the plugin `ordova-background-geolocation-lt` needs cordova-android 7.0. Other solution is to use `Hooks` to delete file before installing plugins. But, I can't use this method with PhoneGap Build.

Thank by advance.

**Comment by janpio** [comment]
Phonegap CLI issues are over here: https://github.com/phonegap/phonegap-cli/issues Please create an issue there if you are having problem with the Phonegap CLI.

**Comment by janpio** [comment]
On a more general note: The error looks like being caused by a plugin that still uses an old path that does not work with cordova-android 7.x. Are you installing the newest version of all plugins?

To solve this, I would suggest you create a new project with the newest CLI and cordova-android, then install the plugins manually with their newest versions. If everything works, you can just copy over your code.

Alternatively you can of course make sure to use the newest versions of everything to fix this.
